import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, confusion_matrix, precision_score, recall_score,
                             f1_score, ConfusionMatrixDisplay)
from sklearn.model_selection import GroupShuffleSplit
import joblib

"""
Filename: cross_validation_species.py
Author: Mili Ostojic
Date: 09-01-2026
Version: 1.0
Description: Perform cross-validation of species identification from the features of the clips in the 5-second clips 
balanced dataset
"""


def cross_validation(excel_address, results_address):
    """Cross validation of species identification"""

    # Read dataset of clips and their corresponding flight pattern features
    vid_dataset = pd.read_excel(excel_address).to_numpy()

    # Remove the clips which did not have a flight pattern successfully generated
    vid_dataset_nons_removed = []
    for i in range(len(vid_dataset)):
        feature = vid_dataset[i][3]
        if feature != "no flight pattern generated":
            vid_dataset_nons_removed.append(vid_dataset[i])

    # Convert the list to a numpy array
    vid_dataset_nons_removed = np.array(vid_dataset_nons_removed)
    print(len(vid_dataset_nons_removed))

    # Retrieve the columns from the array
    vids = vid_dataset_nons_removed[:, 0]
    labels = vid_dataset_nons_removed[:, 1]
    groups = vid_dataset_nons_removed[:, 2]
    features = vid_dataset_nons_removed[:, 3]

    print(labels)

    # Get the indexes of the rows at which the species label changes
    change_indexes = [0]
    prev_label = labels[0]
    for i in range(len(labels)):
        if labels[i] == prev_label:
            continue
        else:
            change_indexes.append(i)
        prev_label = labels[i]

    print(change_indexes)

    # Split up each column into species sections using the identified change indexes
    vid_split = []
    labels_split = []
    groups_split = []
    features_split = []

    for i in range(len(change_indexes)-1):
        vid_split.append(vids[change_indexes[i]:change_indexes[i+1]])
        labels_split.append(labels[change_indexes[i]:change_indexes[i+1]])
        groups_split.append(groups[change_indexes[i]:change_indexes[i+1]])
        features_split.append(features[change_indexes[i]:change_indexes[i+1]])

    final_index = change_indexes[len(change_indexes)-1]
    vid_split.append(vids[final_index:])
    labels_split.append(labels[final_index:])
    groups_split.append(groups[final_index:])
    features_split.append(features[final_index:])

    print(labels_split)

    # Create a GroupShuffleSplit object with 10 splits, 80% train and 20% test and a constant random state
    # GroupShuffleSplit ensures that there is no overlap in original video between the train clips and test clips
    gss = GroupShuffleSplit(n_splits=10, train_size=.8, test_size=.2, random_state=42)

    X_train_by_species = []
    y_train_by_species = []
    X_test_by_species = []
    y_test_by_species = []

    # Cycle through species
    for i in range(len(vid_split)):

        single_species_X_train = []
        single_species_y_train = []
        single_species_X_test = []
        single_species_y_test = []

        # Cycle through training and test sets generated by the GroupShuffleSplit
        for j, (train_index, test_index) in enumerate(gss.split(features_split[i], labels_split[i], groups_split[i])):
            # Retrieve the training features, the test features, the training labels and the test labels for the
            # current split
            X_train_sec = features_split[i][train_index]
            X_test_sec = features_split[i][test_index]
            y_train_sec = labels_split[i][train_index]
            y_test_sec = labels_split[i][test_index]

            print(X_train_sec)
            print(y_train_sec)

            print(y_test_sec)

            # Update the lists of training features, training labels, test features and test labels for the current
            # species with the current split
            single_species_X_train.append(X_train_sec)
            single_species_y_train.append(y_train_sec)
            single_species_X_test.append(X_test_sec)
            single_species_y_test.append(y_test_sec)

        # Update the lists of training features, training labels, test features and test labels with all the splits for
        # the current species
        X_train_by_species.append(single_species_X_train)
        y_train_by_species.append(single_species_y_train)
        X_test_by_species.append(single_species_X_test)
        y_test_by_species.append(single_species_y_test)

    X_train_combos = []
    y_train_combos = []
    X_test_combos = []
    y_test_combos = []

    # Cycles through the splits
    for i in range(len(X_train_by_species[0])):

        X_train_combo = []
        y_train_combo = []
        X_test_combo = []
        y_test_combo = []

        # Cycles through species
        for j in range(len(X_train_by_species)):

            # Combine the 10 splits per species into 10 overall splits of the full dataset
            # E.g. to combine all the first splits of training data for each species
            # i is 0, j changes between 0 and 3
            # Therefore, the below will append red_kite[0], kestrel[0], sparrowhawk[0], black-headed_gull[0]

            for k in range(len(X_train_by_species[j][i])):
                X_train_combo.append(X_train_by_species[j][i][k])
            for k in range(len(y_train_by_species[j][i])):
                y_train_combo.append(y_train_by_species[j][i][k])
            for k in range(len(X_test_by_species[j][i])):
                X_test_combo.append(X_test_by_species[j][i][k])
            for k in range(len(y_test_by_species[j][i])):
                y_test_combo.append(y_test_by_species[j][i][k])

        # Update the lists of overall splits of training features, training labels, test features and test labels
        X_train_combos.append(X_train_combo)
        y_train_combos.append(y_train_combo)
        X_test_combos.append(X_test_combo)
        y_test_combos.append(y_test_combo)

    all_predicted = []
    all_actual = []

    # Create an empty combined matrix
    combined_matrix = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])

    # Cycle through the splits
    for i in range(len(X_train_combos)):

        X_train = []
        y_train = []
        X_test = []
        y_test = []

        # Cycle through the training features in the current split
        for j in range(len(X_train_combos[i])):
            print(X_train_combos[i][j])

            # Retrieve all the feature strings for a single clip (there can be more than one set of features as there
            # can be more than one flight pattern generated for a single clip)
            all_features = X_train_combos[i][j].split(";")

            # Convert each features string into a numerical list
            for features in all_features:
                float_features = []
                if features != '':
                    features_list = features.split(",")
                    for feature in features_list:
                        if feature != '':
                            float_features.append(float(feature))
                    print(float_features)

                    # Update the list of training features for the current split with the numerical feature sets for
                    # each clip and the list of training labels for the current split with the corresponding labels
                    X_train.append(float_features)
                    y_train.append(y_train_combos[i][j])

        # Cycle through the test features in the current split
        for j in range(len(X_test_combos[i])):
            print(X_test_combos[i][j])

            # Retrieve all the feature strings for a single clip (there can be more than one set of features as there
            # can be more than one flight pattern generated for a single clip)
            all_features = X_test_combos[i][j].split(";")

            # Convert each features string into a numerical list
            for features in all_features:
                float_features = []
                if features != '':
                    features_list = features.split(",")
                    for feature in features_list:
                        if feature != '':
                            float_features.append(float(feature))
                    print(float_features)

                    # Update the list of training features for the current split with the numerical feature sets for
                    # each clip and the list of training labels for the current split with the corresponding labels
                    X_test.append(float_features)
                    y_test.append(y_test_combos[i][j])

        # Create a Random Forest Classifier
        rf = RandomForestClassifier()

        print(y_test)

        # Train the Random Forest Classifier on the training features and training labels for the current split
        rf.fit(np.array(X_train), np.array(y_train))

        # Get a prediction of species labels from the test features for the current split
        y_pred = rf.predict(X_test)

        print(y_pred)

        # Calculate the metrics for the current model using the test labels and predicted labels for the current split
        accuracy = accuracy_score(y_test, y_pred)
        balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='weighted')

        # Generate a confusion matrix for the current model (ensuring the species labels are always in the same order)
        matrix = confusion_matrix(y_test, y_pred, labels=("Red Kite", "Kestrel", "Black-headed gull", "Sparrowhawk"))
        print(matrix)

        # Add the confusion matrix to a combined matrix
        combined_matrix += matrix

        # UNCOMMENT BELOW TO PLOT THE CONFUSION MATRIX FOR THE CURRENT SPLIT
        # fig, ax = plt.subplots(figsize=(2, 2))
        # plt.rcParams.update({'font.size': 16})
        #
        # cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix=matrix, display_labels=["Red Kite", "Kestrel",
        #                                                                                      "Black-headed\ngull",
        #                                                                                      "Sparrowhawk"])
        # cm_display.plot(ax=ax)
        # plt.show()

        # UNCOMMENT TO SAVE MODEL TO FILE
        # joblib.dump(rf, "model3.joblib")

        # Update the list of the predictions for all the splits with the predictions for the current split
        for predicted in y_pred:
            all_predicted.append(predicted)
        # Update the list of all the actual labels for all the splits with the actual labels for the current split
        for actual in y_test:
            all_actual.append(actual)

        print(accuracy, balanced_accuracy, precision)

        print("COMBO" + str(i) + "DONE")

    print(combined_matrix)

    # Set the parameters for the combined confusion matrix plot
    plt.rc('font', size=175)
    plt.rc('axes', titlesize=175)

    fig, ax = plt.subplots(figsize=(120, 60))
    plt.rcParams.update({'font.size': 175})

    # Create combined confusion matrix
    combined_matrix = confusion_matrix(all_actual, all_predicted, labels=("Red Kite", "Kestrel", "Black-headed gull",
                                                                          "Sparrowhawk"))
    print(combined_matrix)

    # Create the plot
    cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix=combined_matrix, display_labels=["Red Kite", "Kestrel",
                                                                                                  "Black-headed\ngull",
                                                                                                  "Sparrowhawk"])
    cm_display.plot(ax=ax)

    # Set the title
    plt.title("Group Shuffle Split of M3\non 5-second clips test dataset")

    # Set the x-axis and y-axis labels with a rotation of 90 degrees on the x-axis labels
    plt.yticks([0, 1, 2, 3], ['Red Kite', 'Kestrel', 'Black-\nHeaded Gull', 'Sparrowhawk'], rotation=0)
    plt.xticks([0, 1, 2, 3], ['Red Kite', 'Kestrel', 'Black-\nHeaded Gull', 'Sparrowhawk'], rotation=90)

    # Plot the combined matrix with a tight layout (minimal whitespace)
    plt.tight_layout()

    # Save the combined confusion matrix to file
    plt.savefig(results_address, bbox_inches="tight")

    # plt.show()

    # Calculate the metrics for the combined splits i.e. cross-validation
    accuracy = accuracy_score(all_actual, all_predicted)
    balanced_accuracy = balanced_accuracy_score(all_actual, all_predicted)
    precision = precision_score(all_actual, all_predicted, average='weighted')
    recall = recall_score(all_actual, all_predicted, average='weighted')
    f1 = f1_score(all_actual, all_predicted, average='weighted')
    print(accuracy, balanced_accuracy, precision, recall, f1)


# Change "path/to" to the path to the git folder
address = "path/to/automated-bird-flight-pattern-classification/"
excel_address = address + "Datasets/Dataset excel sheets/5 second clips features.xlsx"
results_address = address + "Results/Actual final/m3 confusion matrix.png"
cross_validation(excel_address, results_address)
